/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProxyImageRouteImport } from './routes/api/proxy-image'
import { Route as ApiPublicUploadSquareRouteImport } from './routes/api/public/upload-square'
import { Route as ApiPublicRemoveBgRouteImport } from './routes/api/public/remove-bg'
import { Route as ApiImgKeyRouteImport } from './routes/api/img/$key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyImageRoute = ApiProxyImageRouteImport.update({
  id: '/api/proxy-image',
  path: '/api/proxy-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUploadSquareRoute = ApiPublicUploadSquareRouteImport.update({
  id: '/api/public/upload-square',
  path: '/api/public/upload-square',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRemoveBgRoute = ApiPublicRemoveBgRouteImport.update({
  id: '/api/public/remove-bg',
  path: '/api/public/remove-bg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImgKeyRoute = ApiImgKeyRouteImport.update({
  id: '/api/img/$key',
  path: '/api/img/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/proxy-image': typeof ApiProxyImageRoute
  '/api/img/$key': typeof ApiImgKeyRoute
  '/api/public/remove-bg': typeof ApiPublicRemoveBgRoute
  '/api/public/upload-square': typeof ApiPublicUploadSquareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/proxy-image': typeof ApiProxyImageRoute
  '/api/img/$key': typeof ApiImgKeyRoute
  '/api/public/remove-bg': typeof ApiPublicRemoveBgRoute
  '/api/public/upload-square': typeof ApiPublicUploadSquareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/proxy-image': typeof ApiProxyImageRoute
  '/api/img/$key': typeof ApiImgKeyRoute
  '/api/public/remove-bg': typeof ApiPublicRemoveBgRoute
  '/api/public/upload-square': typeof ApiPublicUploadSquareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/proxy-image'
    | '/api/img/$key'
    | '/api/public/remove-bg'
    | '/api/public/upload-square'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/proxy-image'
    | '/api/img/$key'
    | '/api/public/remove-bg'
    | '/api/public/upload-square'
  id:
    | '__root__'
    | '/'
    | '/api/proxy-image'
    | '/api/img/$key'
    | '/api/public/remove-bg'
    | '/api/public/upload-square'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiProxyImageRoute: typeof ApiProxyImageRoute
  ApiImgKeyRoute: typeof ApiImgKeyRoute
  ApiPublicRemoveBgRoute: typeof ApiPublicRemoveBgRoute
  ApiPublicUploadSquareRoute: typeof ApiPublicUploadSquareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy-image': {
      id: '/api/proxy-image'
      path: '/api/proxy-image'
      fullPath: '/api/proxy-image'
      preLoaderRoute: typeof ApiProxyImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/upload-square': {
      id: '/api/public/upload-square'
      path: '/api/public/upload-square'
      fullPath: '/api/public/upload-square'
      preLoaderRoute: typeof ApiPublicUploadSquareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/remove-bg': {
      id: '/api/public/remove-bg'
      path: '/api/public/remove-bg'
      fullPath: '/api/public/remove-bg'
      preLoaderRoute: typeof ApiPublicRemoveBgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/img/$key': {
      id: '/api/img/$key'
      path: '/api/img/$key'
      fullPath: '/api/img/$key'
      preLoaderRoute: typeof ApiImgKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiProxyImageRoute: ApiProxyImageRoute,
  ApiImgKeyRoute: ApiImgKeyRoute,
  ApiPublicRemoveBgRoute: ApiPublicRemoveBgRoute,
  ApiPublicUploadSquareRoute: ApiPublicUploadSquareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
